// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "sbG3XOWiWIqA4C3rajskHGFRjD4tS07IyVzou8rrHV9O59xrVcpLqyGgHuLuY22ZkiYmK5";
}
}
}

